//This is AUTOGENERATED FILE by bb-assets-generator-plugin. DO NOT EDIT!!!

export const arrow_svg = "../assets/arrow.svg";
export const lucida_sans_unicode_webfont_woff = "../assets/lucida_sans_unicode-webfont.woff";
export const lucida_sans_unicode_webfont_woff2 = "../assets/lucida_sans_unicode-webfont.woff2";
