//This is AUTOGENERATED FILE by bb-assets-generator-plugin. DO NOT EDIT!!!

export const arrow_svg = "../assets/arrow.svg";
export const dateArrow_svg = "../assets/dateArrow.svg";
export const email_svg = "../assets/email.svg";
export const fb_svg = "../assets/fb.svg";
export const instagram_svg = "../assets/instagram.svg";
export const jakub_jpg = "../assets/jakub.jpg";
export const kontakt_background_png = "../assets/kontakt-background.png";
export const logo_svg = "../assets/logo.svg";
export const lucida_sans_unicode_webfont_woff = "../assets/lucida_sans_unicode-webfont.woff";
export const lucida_sans_unicode_webfont_woff2 = "../assets/lucida_sans_unicode-webfont.woff2";
export const menu_svg = "../assets/menu.svg";
export const phone_svg = "../assets/phone.svg";
export const zakolik_background_png = "../assets/zakolik-background.png";
export const nodog_svg = "../assets/nodog.svg";
export const parking_svg = "../assets/parking.svg";
export const tv_svg = "../assets/tv.svg";
export const wifi_svg = "../assets/wifi.svg";
export const nosmoke_svg = "../assets/nosmoke.svg";
export const banner_jpg = "../assets/banner.jpg";
export const bannerArrow_svg = "../assets/bannerArrow.svg";
